name: Release

on:
  push:
    branches:
      - main  # Trigger release on push to main (or your default branch)
      - 'release/*'  # Optionally trigger for release branches
  pull_request:
    branches:
      - main  # Optional: Trigger PRs for releases

jobs:
  release:
    name: Release Workflow
    runs-on: ubuntu-latest

    permissions:
        contents: write      # Allows pushing commits and creating tags
        actions: write       # Allows creating releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Choose the node version
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
      
      - name: Set Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Update Version & changelog
        run: npx standard-version

      - name: Push changes and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for release
        run: |
          git push --follow-tags origin main

      # - name: Run release-it
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for release
      #   run: |
      #     npx release-it --ci --no-npm
      - name: Get Latest Tag
        id: latest-tag
        run: echo "latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Print Latest Tag
        run: echo "The latest tag is ${{ env.latest_tag }}"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          title: "${{ env.latest_tag }}"